### ISSUE TITLE
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

### ISSUE THREAD

**Issue by radoslawkoziol** [OpenFactorioServerManager/factorio-server-manager#259]
I've cloned the repo and tried to run: ```docker-compose -f docker-compose.simple.yaml up -d```

```
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 189, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

What am I missing there?

**Comment by knoxfighter** [comment]
That is a problem with your docker environment. From a quick google search with the searchterm `  File "docker/transport/unixconn.py", line 43, in connect FileNotFoundError: [Errno 2] No such file or directory` i find a few github issues that have resolved that issue. I'm not going to read what exactly they did, but i would start with checking your user/docker rights.

**Comment by Omaha2002** [comment]
What does systemctl status docker say?

**Comment by radoslawkoziol** [comment]
> What does systemctl status docker say?

Yeah, I've found it in a meantime that docker wasn't running and i fixed it. But now I'm getting
`docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))`. It looks like they've blocked me for too many tries, maybe?

**Comment by knoxfighter** [comment]
You need to add your user to the docker group, so it is allowed to run docker commands.

**Comment by radoslawkoziol** [comment]
> You need to add your user to the docker group, so it is allowed to run docker commands.

yeah, and now `docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))`. I guess there's some digging ahead of me. I'm new with docker on unix

**Comment by mroote** [comment]
This looks to be an issue with network connectivity on your system but not related to the server manager. I'll close this for now.
